module.exports = {
    "ap_id" : { required: true, type: "string"},
"user_id" : { required: true, type: "number"},
"for_ap" : { 
  required: true, 
  type: "string", 
  enum: ["me", "other"]
},
"full_name" : { required: true, type: "string"},
"email_id" : { required: true, type: "string"},
"country_code" : { required: false, type: "number"},
"mobile_no" : { required: true, type: "string"},
"ref_name" : { required: true, type: "string"},
"ref_country_code" : { required: true, type: "string"},
"ref_mobile_no" : { required: true, type: "string"},
"ref_email_id" : { required: true, type: "string"},
"ap_location" : { required: true, type: "number"},
"app_visit" : { required: false, type: "string"},
"city" : { required: false, type: "number"},
"state" : { required: true, type: "number"},
"country" : { required: false, type: "number"},
"designation" : { required: true, type: "string"},
"designationcomp" : { required: true, type: "string"},
"meet_purpose" : { required: true, type: "string"},
"meet_subject" : { required: true, type: "string"},
"no_people" : { required: true, type: "number"},
"no_people_partial" : { required: false, type: "string"},
"from_date" : { required: true, type: "date"},
"to_date" : { required: true, type: "date"},
"tags" : { required: false, type: "string"},
"attachment" : { required: true, type: "string"},
"attachment_url" : { required: false, type: "string"},
"picture" : { required: false, type: "string"},
"secretary_note" : { required: true, type: "string"},
"gurudev_remark" : { required: true, type: "string"},
"assign_to" : { required: true, type: "number"},
"assign_to_fill" : { required: false, type: "string"},
"assigned_by" : { required: false, type: "string"},
"ap_date" : { required: true, type: "date"},
"ap_time" : { required: true, type: "string"},
"star_rate" : { required: true, type: "string"},
"ap_status" : { required: true, type: "string"},
"check_in_status" : { required: true, type: "string"},
"darshan_line" : { required: true, type: "string"},
"backstage_status" : { required: true, type: "string"},
"deleted_app" : { required: true, type: "string"},
"entry_date_time" : { required: true, type: "string"},
"position_order" : { required: true, type: "string"},
"darshan_line_email" : { required: true, type: "string"},
"entry_date" : { required: true, type: "date"},
"mtype" : { required: false, type: "string"},
"zoom_link" : { required: false, type: "string"},
"access_token" : { required: false, type: "string"},
"venue" : { required: false, type: "string"},
"join_url" : { required: false, type: "string"},
"password" : { required: false, type: "string"},
"travelled" : { required: false, type: "string"},
"from_where" : { required: false, type: "string"},
"currently_doing" : { required: false, type: "string"},
"dop" : { required: false, type: "string"},
"selCountry" : { required: false, type: "string"},
"selState" : { required: false, type: "string"},
"selCity" : { required: false, type: "string"},
"toa" : { required: false, type: "string"},
"curr_loc" : { required: false, type: "string"},
"email_status" : { required: false, type: "string"},
"tcode" : { required: false, type: "string"},
"taughtCourses" : { required: false, type: "string"},
"more_info" : { required: true, type: "string"},
"admit_status" : { required: false, type: "string"},
"admitted_by" : { required: false, type: "number"},
"no_people_names" : { required: false, type: "string"},
"no_people_numbers" : { required: false, type: "string"},
"no_people_eleven_details" : { required: false, type: "string"},
"send_schedule" : { required: false, type: "string"},
"arrival_time" : { required: false, type: "string"},
"schedule_date" : { required: false, type: "string"},
"schedule_time" : { required: false, type: "string"},
"schedule_send_status" : { required: false, type: "string"},
"stay_avail" : { required: false, type: "string"},
"slotted_by" : {required: false, type: "string"}
};

// allowed types - number, string, boolean, object, undefined
